### ISSUE TITLE
Question : Caching JWT validation result

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer3.AccessTokenValidation#103]
Is there any reason for caching only reference tokens and not JWT?

**Comment by brockallen** [comment]
JWTs are self-contained and don't need to be sent to IdSvr to validate. Caching for reference tokens saves the round trip.

**Comment by akshetty9** [comment]
Hello Brock Allen... I have read about this. But, in case some one is writing their own API for validation, is there any problem that you see if they want to cache the JWT validation results? If the token is valid for for 30 minutes, it can avoid doing the validation for all calls for that duration and use the results in cache.

**Comment by brockallen** [comment]
Sure. It would avoid the overheard of JWT validation with the trade off of memory consumption.

**Comment by akshetty9** [comment]
ok..I guess then we need to weigh the cost for memory against the time for each validation and decide. Thanks
