### ISSUE TITLE
Discovery endpoint metadata retrieval: retry behavior

### ISSUE THREAD

**Issue by vtylyk** [IdentityServer/IdentityServer3.AccessTokenValidation#104]
**Scenario:** 

IdentityServer is a separate micro-service, other micro-services use it for authentication via JWT tokens.
1. Set `DelayLoadMetadata = true` in middleware options. (Some background: this was done to make Startup of micro-services more reliable and independent from external factors, in this case request to discovery endpoint which might be not available at startup time)
2. Stop the IdentityServer website.
3. Make a request to one of the micro-services which use IdentityServer authentication
4. Start the IdentityServer website.
5. Make the request again

**Expected result:**
Step 3 fails with 

>  "System.InvalidOperationException: IDX10803: Unable to create to obtain configuration from ... "
> exception.

Step 5 succeeds, because IdentityServer is up and running again and metadata can be retrieved.

**Actual result:**

All subsequent requests fail with the same exception. There is no retry behavior for retrieving discovery endpoint metadata.

**Cause:**

`Lazy<T>` is used when initializing LocalValidation (Same situation is in `ConfigureLocalValidation`method.):

```
            if (options.LocalValidationOptions != null)
            {
                _localValidationFunc = new Lazy<AppFunc>(() => 
                {
                    var localBuilder = app.New();
                    localBuilder.UseOAuthBearerAuthentication(options.LocalValidationOptions.Value);
                    localBuilder.Run(ctx => next(ctx.Environment));
                    return localBuilder.Build();

                }, true);
            }

```

Passing **true** is the same as using `LazyThreadSafetyMode.ExecutionAndPublication`. This ensures that only one thread can initialize Lazy<T>, but this also caches exception in case it is thrown during initialization. So all subsequent calls to Lazy<T>.Value will experience the same cached exception thrown every time. In this case the only way to "heal" a micro-service is restart.

I would suggest to use `LazyThreadSafetyMode.PublicationOnly` mode:  multiple threads can invoke the initialization logic but the first thread to complete the initialization successfully sets the value of the Lazy<T> instance. This would make the middleware more fault-tolerant by enabling implicit retry behavior in subsequent requests.

**Comment by leastprivilege** [comment]
Sounds good. We will look into it.

**Comment by leastprivilege** [comment]
Have you verified that this works? Could you send a PR?

**Comment by vtylyk** [comment]
Yes, it works for me. I will send you a PR soon

**Comment by leastprivilege** [comment]
thanks - against the dev branch please.

**Comment by vtylyk** [comment]
Okay, PR is here: https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/pull/106
