### ISSUE TITLE
Incompatibility with System.Net.Http 4.1.0?!

### ISSUE THREAD

**Issue by fabiodiluca** [IdentityServer/IdentityServer3.AccessTokenValidation#105]
I am trying to use this middleware inside a pack that also uses System.Net.Http 4.1.0, but it gives me an exception at this line: 'var handler = options.BackchannelHttpHandler ?? new WebRequestHandler();' (DiscoveryDocumentIssuerSecurityTokenProvider.cs).It says that the class is less accessible than the base class. Is it possible to update this project to use the new nuget System.Net.Http 4.1.0?

**Comment by leastprivilege** [comment]
Where is version 4.1.0 coming from?

**Comment by fabiodiluca** [comment]
Thank you for your super lightining fast feedback. System,Net.Http 4.1.0 is used by refit (popular Rest TypeSafe Client) nuget package. The thing is that i am mixing .Net Standard compatible nuget with this middleware.
![image](https://cloud.githubusercontent.com/assets/19762921/18386161/68057d14-766b-11e6-94fd-6172e61ca724.png)
Inheritance security has been violated by the type "System.Net.WebRequestHandler'. Derived types must correspond to the base type accessibility or be less accessible.
![image](https://cloud.githubusercontent.com/assets/19762921/18386170/8428bae2-766b-11e6-9ef4-beb5369def3e.png)
If I disable(skip) this middleware than I don't get any exceptions.
I am not a developer expert, sorry if I making anything wrong.

**Comment by fabiodiluca** [comment]
It it is indirectly because refit:
![image](https://cloud.githubusercontent.com/assets/19762921/18386342/d8af8e78-766c-11e6-8139-1f4e3f41c3ff.png)
![image](https://cloud.githubusercontent.com/assets/19762921/18386353/ead04f70-766c-11e6-837a-412cbfda130d.png)

**Comment by fabiodiluca** [comment]
I have modified this project(AccessTokenValidation) to use System.Net.Http 4.1.0, what I beleived it would  solve it.I did it, but I was wrong, the error still the same. Can't figure out what is causing this.

**Comment by leastprivilege** [comment]
Yes - the dependencies are incompatible. You should report that to Microsoft.

It is not even our code using the HttpClient - but Microsoft's OpenID Connect library.

**Comment by fabiodiluca** [comment]
Are you sure they are incompatible? I don't even know if I am doing something wrong.

**Comment by leastprivilege** [comment]
Maybe this other library should also have a pain .NET compilation target - this way it wouldn't force you to use the CoreFX libs.

Anyways - this is not an identityserver issue. closing for now. feel free to re-open when you have new infos

**Comment by fabiodiluca** [comment]
Just updating info: I discovered that System.Net.Http 4.1.0 has a critical security problem that makes it not working on .net.4.6.1. https://github.com/dotnet/corefx/issues/11100
