### ISSUE TITLE
IdentityServer3.AccessTokenValidation.2.11.0 is not strongly named

### ISSUE THREAD

**Issue by vipallav** [IdentityServer/IdentityServer3.AccessTokenValidation#119]
Hi,

I am updating to IdentityServer3.AccessTokenValidation.2.11.0 but since my project use strong key this NuGet package is not getting build and giving error of strongly names. Please find the exact error here-

Could not load file or assembly 'IdentityServer3.AccessTokenValidation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) 

Any help would be appreciated. 
Thanks in advance. :)

**Comment by leastprivilege** [comment]
We don't provide strong named versions of our assemblies.

Maybe this will help you:
https://github.com/dsplaisted/strongnamer

**Comment by vipallav** [comment]
Thanks for the quick response. :)

But as I can see in previous version it was strongly named. Is some approach is changed recently? Even for the same version I upgraded the packages and I got strongly named dll but when I am trying today It's not strongly named. Also I used to get this file "IdentityServer3.AccessTokenValidation.dll.unsigned" with the package but not getting now when trying to install.

**Comment by leastprivilege** [comment]
We never published strong named assemblies. I am not sure what you are talking about ;)

**Comment by vipallav** [comment]
oho but now sure how I got the attached package which has strong named assembly.

[IdentityServer3.AccessTokenValidation.2.11.0.zip](https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/files/565624/IdentityServer3.AccessTokenValidation.2.11.0.zip)

**Comment by leastprivilege** [comment]
no - sorry.

**Comment by vipallav** [comment]
:(
