### ISSUE TITLE
Claims translated to WIF for JWT access tokens

### ISSUE THREAD

**Issue by null-d3v** [IdentityServer/IdentityServer3.AccessTokenValidation#123]
When using JWT access tokens, any claim with a WIF equivalent is translated into a WIF claim on the ClaimsPrincipal. However, when using reference access tokens, the claims are set on the ClaimsPrincipal with their OIDC names.

For example:

- Reference access token: OIDC sub claim
- JWT access token: WIF NameIdentifier claim

**Comment by brockallen** [comment]
You should call `JstSecurityTokenHandler.InboundClaimTypeMap.Clear()` to normalize them.
