### ISSUE TITLE
IIS hosting and Stage Markers

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3.AccessTokenValidation#127]
For IIS hosted owin middleware, would it be advisable to do app.UseStageMarker(PipelineStage.Authenticate) after registering the token validation middleware to ensure it runs at the right stage in the owin pipeline? Are there any known issues with not doing so (which will have it run way later in PreHandlerExecute stage)?

Thanks

**Comment by leastprivilege** [comment]
Are you seeing any issues if you don't set the stage marker?

**Comment by snothub** [comment]
No, but I wanted to ask about any potentially known issues since I'm not convinced my tests are bullet-proof.

**Comment by leastprivilege** [comment]
You only need to set stage markers if you need to co-op with legacy HTTP modules that run at certain stages you you need a specific ordering.
