### ISSUE TITLE
Set audience to the resource I want to use

### ISSUE THREAD

**Issue by mrochon** [IdentityServer/IdentityServer3.AccessTokenValidation#130]
As per https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/8 audience seems to be always set to issuer+/resource. However, per JWT specs (as I understand them) my access token should have an aud claim that identifies the resource I am providing the token to. Is there a way to configure IS with a list of valid audiences (per client) and include the appropriate aud claim in the token?

**Comment by leastprivilege** [comment]
You use the scope claim to specify the exact API this token is for.

**Comment by mrochon** [comment]
Yes, but that still does not change my aud claim in the token and so the validation will fail unless every API app uses the same audience id.

**Comment by leastprivilege** [comment]
Yes - in OAuth scopes are used. Aud is a JWT implementation detail.

That's the way it is in IdentityServer3.

**Comment by mrochon** [comment]
OK. Thanks.

**Comment by UlyssesAlves** [comment]
Do you guys have a code example of how to accomplish this?
