### ISSUE TITLE
How to Validate Access Token Issued by IdentityServer3 on .NET Core 1.1 

### ISSUE THREAD

**Issue by h2chch** [IdentityServer/IdentityServer3.AccessTokenValidation#131]
Hi,
I have API built on top .NET Core 1.1 stack and now I want to validate the access token issued by IdentityServer3. How can I achieve this? I have tried to use this IdentityServer3.AccessTokenValidation nuget package but is having incompatibilities issues with .NET Core 1.1. Is there any workaround for this problem?

**Comment by leastprivilege** [comment]
see here:

https://github.com/IdentityServer/CrossVersionIntegrationTests

**Comment by h2chch** [comment]
Thank you for the sample of projects (Core API with IS3). One more question, when I use IdentityServer4.AccessToken package, is ApiSecret mandatory?

**Comment by leastprivilege** [comment]
No - only when using reference tokens.
