### ISSUE TITLE
Update The Nuspec To Include Dependency On 

### ISSUE THREAD

**Issue by mickdelaney** [IdentityServer/IdentityServer3.AccessTokenValidation#134]
The nupsec doesnt include System.IdentityModel.Tokens.Jwt, so nuget automatically upgrades it to 5.1.2, which breaks at runtime when calling 

app.UseIdentityServerBearerTokenAuthentication(AuthOptions);

from the source
https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/master/source/AccessTokenValidation/packages.config

<package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net45" />

**Comment by leastprivilege** [comment]
PR?

**Comment by mickdelaney** [comment]
ok cool !!
