### ISSUE TITLE
Trying to validate AccessToken using Accesstokenvalidate Endpoint

### ISSUE THREAD

**Issue by Nagesh1987** [IdentityServer/IdentityServer3.AccessTokenValidation#142]
I am using Hybrid flow for my client application, when I call the AccessTokenvalidation endpoint I am not receiving any response on examining of the log file I see the following.

iisexpress.exe Information: 0 : 2017-04-04 19:27:32.971 +05:30 [Information] Start access token validation
2017-04-04 19:27:32.971 +05:30 [Debug] Cache hit: mvc.owin.hybrid
iisexpress.exe Information: 0 : 2017-04-04 19:27:32.971 +05:30 [Information] "Token validation success"
"{
  \"ValidateLifetime\": true,
  \"AccessTokenType\": \"Reference\",
  \"ExpectedScope\": \"openid\",
  \"TokenHandle\": \"66b379fc746b7ff2ed8de0ed4c6f1f09\",
  \"Claims\": {
    \"aud\": \"https://localhost:44333/core/resources\",
    \"iss\": \"https://localhost:44333/core\",
    \"nbf\": 1491314252,
    \"exp\": 1491317852,
    \"client_id\": \"mvc.owin.hybrid\",
    \"scope\": [
      \"openid\",
      \"profile\",
      \"read\",
      \"write\",
      \"offline_access\"
    ],
    \"sub\": \"88421113\",
    \"auth_time\": 1491314250,
    \"idp\": \"idsrv\",
    \"amr\": \"password\"
  }
}"

Can somebody guide me if I am missing something

**Comment by brockallen** [comment]
wrong repo, but there's not much info from what you've described.
