### ISSUE TITLE
Add UserInfo claims to User.Claims

### ISSUE THREAD

**Issue by mniak** [IdentityServer/IdentityServer3.AccessTokenValidation#158]
Would it be useful add an option that makes the middleware fetch the UserInfo endpoint and add these claims to the principal claims collection?

Many of my APIs are already doing this but on a whole new step.

I am willing to contribute if you thing this is relevant to the project and if I'm doing this the right way.

**Comment by brockallen** [comment]
Userinfo is not for an API to consume. It's meant for a client to consume.

**Comment by mniak** [comment]
Please, help me understand the whole picture:
Why wouln't be appropriate for an API to consume the UserInfo endpoint?
How are the APIs suppose fetch the info about the token's user?

**Comment by brockallen** [comment]
> Please, help me understand the whole picture:

You will have to spend the time and read the specs, unless you're looking to hire us for consulting.

>  How are the APIs suppose fetch the info about the token's user?

Introspection or the claims are in the token itself.

**Comment by mniak** [comment]
I am realizing that I shouldn't call the UserInfo endpoint from the API, but rather configure my API's scope to include some the claims I want to know about.

Thanks
