### ISSUE TITLE
Web Api with IS3 authenticate with IS4 Server

### ISSUE THREAD

**Issue by luigi108** [IdentityServer/IdentityServer3.AccessTokenValidation#162]
Hi,

I have created my authentication server with IS4, by architecture our web api can not be developed in Net Core, so our web api is with Net Framework 4.7 will have AccessTokenValidation of IS3; my question is how should I configure my web api with IS3 to be authenticated in IS4. I searched the internet and found nothing, I would appreciate your help (example).

Thanks and excuse my English

**Comment by brockallen** [comment]
We have cross-version tests to show some of this: https://github.com/IdentityServer/CrossVersionIntegrationTests

**Comment by luigi108** [comment]
Hi,
Thank you very much, it was what I needed; I already tested it and it works correctly.
