### ISSUE TITLE
setting a custom provider on IdentityServerBearerTokenAuthenticationOptions doesn't work

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/IdentityServer3.AccessTokenValidation#26]
As noted [here](https://github.com/IdentityServer/IdentityServer3/issues/1072) setting a custom provider or setting a custom function to the OnRequestToken of the default provider does not work.  Here are my examples

        app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
        {
            Authority = "https://localhost:44300/identity",
            RequiredScopes = new[] {"csRA"},
            Provider = new CustomOAuthBearerProvider("access_token")
        });

or here
````
    var options = new IdentityServerBearerTokenAuthenticationOptions
        {
            Authority = "https://login.codysoft.net/identity",
            RequiredScopes = new[] {"csRA"},
            Provider = new OAuthBearerAuthenticationProvider
            {
                OnRequestToken = context =>
                {
                    var request = context.Request;
                    if (request.Headers.ContainsKey("Authorization"))
                        context.Token = request.Headers["Authorization"];
                    else if (request.Cookies["access_token"] != null)
                        context.Token = request.Cookies["access_token"];
                    else
                    {
                        var value = request.Query.Get("access_token");
                        if (!string.IsNullOrEmpty(value))
                        {
                            context.Token = value;
                        }
                    }
                    return Task.FromResult<object>(null);
                }
            },
        };

        app.UseIdentityServerBearerTokenAuthentication(options);
````
no break point is hit in either sample.  It appears to be ignored completely.

**Comment by leastprivilege** [comment]
I just tried it - and can't repro. Are you on the latest version?

**Comment by stevenfirstrowinc** [comment]
ugh! no.  This is one of the ones I missed the update to when you guys switched names.  It never showed up in my updated package list.  Sorry for the confusion.  Perhaps it's even the reason I'm having problems with SuppressDefaultHostAuthentication.  Thank you.
