### ISSUE TITLE
How to add header to validation endpoint request?

### ISSUE THREAD

**Issue by appetere** [IdentityServer/IdentityServer3.AccessTokenValidation#27]
I've configured the logging in IdentityServer3 to record a correlation ID, if this is sent in a header.

When using the `UseIdentityServerBearerTokenAuthentication` extension, I'd like to be able to add such a correlation header before the request is made in `ValidationEndpointTokenProvider.ReceiveAsync`.

I can copy and paste the whole of `ValidationEndpointTokenProvider' and replace the line:

    var response = await _client.GetAsync(url);

with something like:

```
var request = new HttpRequestMessage(HttpMethod.Get, url);
var correlationId = context.Request.GetCorrelationId();
request.SetCorrelationId(correlationId);
var response = await _client.SendAsync(request);
```

But I would then have to copy & paste `IdentityServerAccessTokenValidationAppBuilderExtensions` as the `ValidationEndpointTokenProvider` is hard-coded:

```
        internal static void UseValidationEndpoint(this IAppBuilder app, IdentityServerBearerTokenAuthenticationOptions options)
        {
            if (options.EnableValidationResultCache)
            {
                if (options.ValidationResultCache == null)
                {
                    options.ValidationResultCache = new InMemoryValidationResultCache(options);
                }
            }

            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
            {
                AccessTokenProvider = new ValidationEndpointTokenProvider(options),
                Provider = options.Provider
            });
        }
```

So I was wondering if one of the following might be possible:

- Make the AccessTokenProvider an option on IdentityServerBearerTokenAuthenticationOptions 
- Expose a callback to allow the HttpRequestMessage to be modified before a call is made to the validation endpoint, eg 

```
public Action<AuthenticationTokenReceiveContext, HttpRequestMessage) PreReceiveCallback {get; set;}

PreReceiveCallback = (context, request) => {
   var correlationId = context.Request.GetCorrelationId();
   request.SetCorrelationId(correlationId);
}
```

**Comment by leastprivilege** [comment]
Couldn't you use the BackChannelHttpHandler on the options to add the header?

**Comment by appetere** [comment]
A problem with setting a BackChannelHttpHandler is that the handler needs access to the per-request IOwinContext.

This would need something similar to the IdentityServer3 AutofacContainerMiddleware to add IOwinContext to the container's current scope, then the handler would need access to the container, to resolve IOwinContext when required.  BUT we're currently using Castle Windsor which doesn't support registering instances within a scope as Autofac can do.

I can probably find some way round this using the BackChannelHttpHandler, so thanks for the suggestion.  It is just that the IOwinContext is already available in the ValidationEndpointTokenProvider's method:

    ReceiveAsync(AuthenticationTokenReceiveContext context)

so would be good to find a way to use the available context, without the handler having to get a copy independently.

**Comment by brockallen** [comment]
Is there still an open issue here, or can we close this?

**Comment by appetere** [comment]
Let's close the issue.  

I haven't spent more time on this yet, but will investigate using the BackChannelHttpHandler as Dominick suggested.
