### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication error

### ISSUE THREAD

**Issue by george-pancescu** [IdentityServer/IdentityServer3.AccessTokenValidation#29]
You have an inconsistency in your code:
- **ScopeRequirementMiddleware** has a ctor which expects a string array of scopes (**string[]**)
- while **IdentityServerBearerTokenAuthenticationOptions** exposes the above mentioned scopes as an **IEnumerable<string>** (these scopes from the option class are further used in your code to determine whether or not to inject the ScopeRequirementMiddleware in the pipeline)

This means that you expect to assign an array of strings (string[]) with an IEnumerable<string>... which I don't think you will succeed :)... (only the other way around is possible)

Getting back to your code
* below code will work OK
``` c#
var authOptions = 
new IdentityServerBearerTokenAuthenticationOptions
        {
            Authority = "https://localhost:44333",
            RequiredScopes = new[] { "api1" }
        });
app.UseIdentityServerBearerTokenAuthentication(authOptions);
```
This will work due to the fact that even though RequiredScopes is an IEnumerable<string>, you instantiate it with an array of strings; this means that 
**typeof(string[]).IsInstanceOf(authOptions.RequiredScopes)  = TRUE**

* However, if one would use the IEnumerable<string> like it was meant to be used, meaning using yield operator... surprise, surprise: MissingMethodException on ScopeRequirementMiddleware (no ctor was found that takes 2 params)
The error comes from Owin, which looks for a matching ctor for a Middleware, by checking its params.
``` C#
var authOptions = new IdentityServerBearerTokenAuthenticationOptions
        {
            Authority = "https://localhost:44333",
            RequiredScopes = GetScopes()
        });
app.UseIdentityServerBearerTokenAuthentication(authOptions);

private static IEnumerable<string> GetScopes()
{
      yield return "api1";
}
```
**typeof(string[]).IsInstanceOf(authOptions.RequiredScopes)  = FALSE** -> thus no ctor matching
 
PS: Owin casts the params of the middleware to an object array

**Comment by leastprivilege** [comment]
That has been fixed on the dev branch.
