### ISSUE TITLE
AuthenticationType ignored

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3.AccessTokenValidation#32]
It seems like passing the option `AuthenticationType` is ignored and always results in "Bearer" being used.

I'm doing:

```C#
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions()
{
    AuthenticationType = "Whatever",
    ...
});
```

Then, I change the filter for the WebAPI to:

```C#
config.Filters.Add(new HostAuthenticationFilter("Whatever"));
```

and change the request header to:

```
Authorize: Whatever <token_here>
```

But this doesn't work, always getting 401 back from the WebAPI. If I revert the filter and request header to "Bearer" (leaving the `options.AuthenticationType` set to `Whatever`), it works again.

Any idea what I might be doing wrong or isn't it supposed to work this way?

**Comment by leastprivilege** [comment]
The authentication type is not related to the scheme name on the authorization header. It is just the name of the middleware.

**Comment by huysentruitw** [comment]
Ok, that explains it. Thanks.
