### ISSUE TITLE
Pass AuthenticationMode option when using ValidationMode.ValidationEndpoint

### ISSUE THREAD

**Issue by KautskyLozanoV** [IdentityServer/IdentityServer3.AccessTokenValidation#36]
I was trying to use OWIN Cookie Authentication for MVC with Active AuthenticationMode and UseIdentityServerBearerTokenAuthentication middleware for WebAPI with Passive AuthenticationMode but this option is never set when using ValidationEndpoint ([here](http://stackoverflow.com/questions/31550388/get-bearer-token-from-owin-cookie-and-put-it-on-api-requests/31574635#31574635))

```
internal static void UseValidationEndpoint(this IAppBuilder app, IdentityServerBearerTokenAuthenticationOptions options)
        {
            if (options.EnableValidationResultCache)
            {
                if (options.ValidationResultCache == null)
                {
                    options.ValidationResultCache = new InMemoryValidationResultCache(options);
                }
            }

            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
            {
                AccessTokenProvider = new ValidationEndpointTokenProvider(options),
                Provider = options.Provider,
            });
        }
``` 
It would be nice to have this options so we could use this middleware on a passive authentication mode

**Comment by leastprivilege** [comment]
should be fixed on dev / RC2
