### ISSUE TITLE
Consider still check expiration for incoming tokens when caching

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3.AccessTokenValidation#41]
I don't think the middleware is currently checking the token expiration if the token is found in the cache. It might make sense to do so.

**Comment by leastprivilege** [comment]
I thought thats been taken care of.. need to double check.

**Comment by brockallen** [comment]
It seems that the token introspection endpoint does not support `exp`. Also there doesn't seem to be a way to indicate an expiration when adding an item to the token cache. Finally, if we ever add sliding expirations then this will be more and more difficult to keep the cache up to date. 

I'll close, but we should be aware that a high cache duration could allow an access token to be used beyond its configured expiration.
