### ISSUE TITLE
MVC6 Action still being called when token is expired

### ISSUE THREAD

**Issue by geraldfvds** [IdentityServer/IdentityServer3.AccessTokenValidation#42]
So I have an MVC6 application, with an Identity Server, and another web application that uses AccessTokenValidation for JWTs with local validation. (I tried Authority and it has the same problem).

On the secondary app I have a controller action with an Authorize attribute. When I invoke this action, I see that there is a first chance SecurityTokenExpiredException with a message of "Lifetime validation failed. The token is expired."

But the action is still called, with a principal that has no claims.

If I call the action without a token, I get a 401.

Is this the expected behavior? And if not, is this likely to be something specific to MVC6 that is just not supported yet? It seems to me that a 401 response would be more appropriate, but I may be mistaken about that :)

**Comment by leastprivilege** [comment]
I haven't tested with MVC6 yet. The built-in MW works just fine, so you might use this one for the time being.

http://leastprivilege.com/2015/07/22/the-state-of-security-in-asp-net-5-and-mvc-6-oauth-2-0-openid-connect-and-identityserver/
