### ISSUE TITLE
Add a "PreserveAccessToken" option

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3.AccessTokenValidation#44]
saves the token as a claim. probably on by default.

**Comment by billpratt** [comment]
:+1:

**Comment by leastprivilege** [comment]
done on dev/myget - please test. thx

**Comment by billpratt** [comment]
![image](https://cloud.githubusercontent.com/assets/2847527/9658814/3b481d52-521a-11e5-80cd-3b11db97feb4.png)

**Comment by billpratt** [comment]
Do you have an idea when this could be release to nuget.org?

**Comment by leastprivilege** [comment]
Soon - i will make it opt-in though.

— 
cheers
Dominick Baier


On 3 Sep 2015 at 15:31:18, Bill Pratt (notifications@github.com) wrote:

Do you have an idea when this could be release to nuget.org?

**Comment by leastprivilege** [comment]
Done 2.1.0

— 
cheers
Dominick Baier


On 3 Sep 2015 at 17:36:56, Dominick Baier (dbaier@leastprivilege.com) wrote:

Soon - i will make it opt-in though.

— 
cheers
Dominick Baier


On 3 Sep 2015 at 15:31:18, Bill Pratt (notifications@github.com) wrote:

Do you have an idea when this could be release to nuget.org?

**Comment by billpratt** [comment]
Thanks!
