### ISSUE TITLE
ASP.net 5 mv6 support

### ISSUE THREAD

**Issue by justsayno** [IdentityServer/IdentityServer3.AccessTokenValidation#56]
Hi, I'm not sure if I am just being dense but I try to install either version of IdentityServer3.AccessTokenValidation (2.3 or 1.2.2) and neither of them seem to get referenced correctly for me..

They both list dependency of:

```
Microsoft.AspNet.WebApi.Client (>5.2.2).
```

Does this work with MV6? If so what am I doing wrong?  Or is the correct approach to use:

```
app.UseOAuthBearerAuthentication(options =>
            {
                options.Authority = “https://localhost:44300″;
                options.Audience = “https://localhost:44300/resources”;
                options.AutomaticAuthentication = true;
            });
```

**Comment by mikeandersun** [comment]
https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/34

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by leastprivilege** [comment]
If anybody wants to work on that - feel free. I am too busy right now.

**Comment by tugberkugurlu** [comment]
I am willing to look at this. Which approach would you like to do this?

 - provide a middleware for ASP.NET 5  natively and forget about OWIN support?
 - provide a middleware natively for both OWIN and ASP.NET 5?
 - use OWIN bridge to plug it in [like this](https://github.com/tugberkugurlu/ModernShopping/blob/5ebf9ff374442e49eecf6b7c574fbd6449743fb5/Auth/src/ModernShopping.Auth.SampleApp/Startup.cs#L184-L208) (currently not working due to #60)?

**Comment by leastprivilege** [comment]
Cool!

A pure ASP.NET 5 MW would be best. With the same feature set as the Katana one (at least that would be the end-goal).

I will work on compiling IdentityModel for DnxCore soon - which includes some of the base functionality.

**Comment by tugberkugurlu** [comment]
Cool, I think as a first pass, making this work under dnx451 should be sufficient.

**Comment by tugberkugurlu** [comment]
assign this issue to me whenever you think it's OK to start.

**Comment by leastprivilege** [comment]
We added you to a new team - and there is also a new repo 

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation

go! ;)

**Comment by tugberkugurlu** [comment]
Cool, I will get on that!

**Comment by leastprivilege** [comment]
dnxcore should actually not be a problem.
