### ISSUE TITLE
don't connect the authority during pipeline build

### ISSUE THREAD

**Issue by tugberkugurlu** [IdentityServer/IdentityServer3.AccessTokenValidation#57]
It currently tries to connect to authority in several cases (I guess) and it blows up if the authority is not there at that time. This is especially a problem on the dev time like when you use docker compose to get your solution up and running and cannot guarantee which one will start before.

The solution would be to wrap the logic inside `Lazy` and reach out to its value on first request.

**Comment by leastprivilege** [comment]
but do you want to find out that something is wrong at startup time - or some time later?

**Comment by tugberkugurlu** [comment]
some time later. In my case, it will blow up 80% of the time for me [unless I do some horrible hacks](https://github.com/tugberkugurlu/ModernShopping/blob/jgfw-auth/Auth/src/ModernShopping.Auth.SampleApp/Startup.cs#L165-L167) :smile: 

If not acceptable to do this by default, it would be good to have an option to evaluate everything lazily through options.

**Comment by leastprivilege** [comment]
I like the idea of having an option for lazy loading...PR? ;)

**Comment by tugberkugurlu** [comment]
yep, will send one.

**Comment by uncleyo** [comment]
I was about to suggest the same thing.
At least in my apps, it's not ok for this to prevent application from starting. I would very much want the protected resources to return 401 until the authority is up and let everything else work (including health monitoring, etc...).

**Comment by leastprivilege** [comment]
yep agreed it would be useful to have an option for lazy loading - but I won't have resources to implement it any time soon.

**Comment by leastprivilege** [comment]
PR anyone? :)

**Comment by tugberkugurlu** [comment]
I will do that.

**Comment by brockallen** [comment]
Can this be closed now?

**Comment by leastprivilege** [comment]
There is a delay load option now.
—
cheers
Dominick Baier
