### ISSUE TITLE
don't new up AppBuilder

### ISSUE THREAD

**Issue by tugberkugurlu** [IdentityServer/IdentityServer3.AccessTokenValidation#58]
this: https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/d983c78c9d8e7daa9991c90ad952c3b7805e842c/source/AccessTokenValidation/IdentityServerBearerTokenValidationMiddleware.cs#L55-L58

Huge problem when trying to run under ASP.NET 5. See https://github.com/tugberkugurlu/ModernShopping/issues/4

**Comment by brockallen** [comment]
Why? This seems like an implementation detail, since it's just another Func in the OWIN pipeline.

**Comment by tugberkugurlu** [comment]
@brockallen yes, it is an implementation detail but [it makes this fail under mono](https://github.com/tugberkugurlu/ModernShopping/issues/4) as the default properties doesn't work for it. Also, you should be honoring user's choice (e.g [logging, data protection](https://github.com/tugberkugurlu/ModernShopping/blob/5ebf9ff374442e49eecf6b7c574fbd6449743fb5/Auth/src/ModernShopping.Auth.SampleApp/Startup.cs#L184-L209), etc.), not new up a new `AppBuiler` from scratch.

**Comment by brockallen** [comment]
Ah ok -- yes, the new one should be created from the top level one. Yep.

**Comment by tugberkugurlu** [comment]
I can confirm that this is fixed in #60.

**Comment by tvdburgt** [comment]
I ran in to the same problem when applying SetDataProtectionProvider. Nice work!
