### ISSUE TITLE
ScopeRequirementMiddleware does not check for presence of access token

### ISSUE THREAD

**Issue by vtylyk** [IdentityServer/IdentityServer3.AccessTokenValidation#66]
Current implementation of ScopeRequirementMiddleware has the following code:

```c#
// if no token was sent - no need to validate scopes
var principal = context.Authentication.User;
if (principal == null || principal.Identity == null || !principal.Identity.IsAuthenticated)
{
  await _next(env);
  return;
}
```

But this does not take into account that multiple authentication mechanisms could be used and principal could be already set by e.g Cookie Authentication beforehand. In this case ScopeRequirementMiddleware returns **insufficient_scope** even when there is no token.

The fix is to check for presence of *idsrv:tokenvalidation:token* in OWIN environment. If you agree I can fire a PR.

Having both Cookie and OAuth authentication schemes together might seem weird, but this still could be the case, for example when custom API (using IdentityServer3.AccessTokenValidation) is being a plugin of Identity Server (which relies on Cookie authentication).

**Comment by leastprivilege** [comment]
Would that work for you? https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/pull/67

Nuget here: https://www.myget.org/F/identity/

**Comment by vtylyk** [comment]
Yeah, it works.
Btw, it has not been merged into DEV, so I could not use the Nuget you provided, had to build it on my own.

**Comment by leastprivilege** [comment]
I will merge it now.

**Comment by vtylyk** [comment]
Thanks!
