### ISSUE TITLE
Authorization header being stripped  - can I configure to use X-Authorization header name

### ISSUE THREAD

**Issue by richardjharding** [IdentityServer/IdentityServer3.AccessTokenValidation#68]
We have a situation on a large public sector intranet where the network infrastructure is stripping the "Authorization" header preventing us from using that to pass the JWT token value

In testing it looks like any header with a "X-" prefix is not stripped - is there a way to configure token validation so that I could look and handle a token in a header with name "X-Authorization" ?

**Comment by leastprivilege** [comment]
yes - using a token provider

see here for a similar example using a query string parameter

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/master/source%2FAccessTokenValidation.Tests%2FIntegration%20Tests%2FTokenProvider.cs#L28

**Comment by richardjharding** [comment]
perfect! thanks for the quick response
