### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication always returns "Anonymous Identity"

### ISSUE THREAD

**Issue by aseemflowingly** [IdentityServer/IdentityServer3.AccessTokenValidation#69]
I am trying to get this working but somehow OWIN isn't calling the access token validation endpoint or is being refused by the Identity server.

The setup is that there are three apps Identity Server 3 (web host), MVC App and Web Api. 

I get the access token from IdSrvr3 

    var client = new TokenClient("https://localhost:44300/core/connect/token", "portal",
                "secret");
    var response = client.RequestResourceOwnerPasswordAsync("username", "password","api").Result;

Then set this token and call an API method from the Web API app.

    var apiClient = new HttpClient();
    apiClient.SetBearerToken(response.AccessToken);

The startup.cs for Web API app is

    public void Configuration(IAppBuilder app)
        {
            // turn off any default mapping on the JWT handler
            JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();

            // accept access tokens from identityserver and require a scope of 'api'
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44300/core",
                ValidationMode = ValidationMode.ValidationEndpoint,

                RequiredScopes = new[] {"api"}
                
            });
        }

When I make that call, I can see that the HttpContext coming into the Authorize attribute, has the authorization header with the token:
![image](https://cloud.githubusercontent.com/assets/16090447/12187472/1829cf7c-b611-11e5-86cc-a259865781ea.png)

But inside the controller method (workflow in this case) the identity is anonymous:

![image](https://cloud.githubusercontent.com/assets/16090447/12187598/1a0fa82e-b612-11e5-8edf-97f7869948f9.png)

What could be wrong?

**Comment by brockallen** [comment]
Look in the IdSvr logs to see what it says when the token is sent for validation.

**Comment by aseemflowingly** [comment]
I checked the IIS Express logs for the IdSvr , there is no entry for the token validation request.

    #Software: Microsoft Internet Information Services 10.0
    #Version: 1.0
    #Date: 2016-01-08 01:05:39
    #Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent)   cs(Referer) sc-status sc-substatus sc-win32-status time-taken
    2016-01-08 01:05:39 ::1 POST /core/connect/token - 44300 - ::1 - - 200 0 0 9417

This is all there is!

**Comment by brockallen** [comment]
No, I mean the identityserver logs.

**Comment by aseemflowingly** [comment]
The identity server logs come up with this:

    iisexpress.exe Information: 0 : 2016-01-08 14:41:41.663 +13:00 [Information] Starting IdentityManager configuration
	iisexpress.exe Warning: 0 : 2016-01-08 14:41:41.958 +13:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
	iisexpress.exe Warning: 0 : 2016-01-08 14:41:41.959 +13:00 [Warning] TokenHandleStore not configured - falling back to InMemory
	iisexpress.exe Warning: 0 : 2016-01-08 14:41:41.959 +13:00 [Warning] ConsentStore not configured - falling back to InMemory
	iisexpress.exe Warning: 0 : 2016-01-08 14:41:41.959 +13:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
	iisexpress.exe Information: 0 : 2016-01-08 14:41:42.447 +13:00 [Information] Start token request
	2016-01-08 14:41:42.474 +13:00 [Debug] Start client validation
	2016-01-08 14:41:42.476 +13:00 [Debug] Start parsing for X.509 certificate
	2016-01-08 14:41:42.476 +13:00 [Debug] client_id is not found in post body
	2016-01-08 14:41:42.478 +13:00 [Debug] Start parsing for secret in post body
	2016-01-08 14:41:42.478 +13:00 [Debug] No secret in post body found
	2016-01-08 14:41:42.479 +13:00 [Debug] Start parsing Basic Authentication secret
	2016-01-08 14:41:42.480 +13:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
	iisexpress.exe Information: 0 : 2016-01-08 14:41:42.481 +13:00 [Information] Secret id found: "portal"
	2016-01-08 14:41:42.485 +13:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
	iisexpress.exe Information: 0 : 2016-01-08 14:41:42.486 +13:00 [Information] Client validation success
	iisexpress.exe Information: 0 : 2016-01-08 14:41:42.489 +13:00 [Information] Start token request validation
	iisexpress.exe Information: 0 : 2016-01-08 14:41:42.493 +13:00 [Information] Start password token request validation
	iisexpress.exe Information: 0 : 2016-01-08 14:41:44.566 +13:00 [Information] Password token request validation success.
	iisexpress.exe Information: 0 : 2016-01-08 14:41:44.653 +13:00 [Information] Token request validation success
	 {
	  "ClientId": "portal",
	  "ClientName": "Admin Portal",
	  "GrantType": "password",
	  "Scopes": "api",
	  "UserName": "username",
	  "AuthenticationContextReferenceClasses": [],
	  "Raw": {
		"grant_type": "password",
		"username": "username",
		"password": "******",
		"scope": "api"
	  }
	}
	iisexpress.exe Information: 0 : 2016-01-08 14:41:44.655 +13:00 [Information] Creating token response
	iisexpress.exe Information: 0 : 2016-01-08 14:41:44.656 +13:00 [Information] Processing token request
	2016-01-08 14:41:44.660 +13:00 [Debug] Creating access token
	2016-01-08 14:41:44.667 +13:00 [Debug] Creating reference access token
	iisexpress.exe Information: 0 : 2016-01-08 14:41:44.670 +13:00 [Information] End token request
	iisexpress.exe Information: 0 : 2016-01-08 14:41:44.675 +13:00 [Information] Returning token response.
	iisexpress.exe Information: 0 : [Owin.IdentityManagerAppBuilderExtensions]: 08-Jan-16 1:46:16 AM -- Starting IdentityManager configuration
	iisexpress.exe Warning: 0 : 2016-01-08 14:46:17.262 +13:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
	iisexpress.exe Warning: 0 : 2016-01-08 14:46:17.271 +13:00 [Warning] TokenHandleStore not configured - falling back to InMemory
	iisexpress.exe Warning: 0 : 2016-01-08 14:46:17.271 +13:00 [Warning] ConsentStore not configured - falling back to InMemory
	iisexpress.exe Warning: 0 : 2016-01-08 14:46:17.271 +13:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
	iisexpress.exe Information: 0 : 2016-01-08 14:46:17.889 +13:00 [Information] Start token request
	2016-01-08 14:46:17.926 +13:00 [Debug] Start client validation
	2016-01-08 14:46:17.928 +13:00 [Debug] Start parsing for X.509 certificate
	2016-01-08 14:46:17.929 +13:00 [Debug] client_id is not found in post body
	2016-01-08 14:46:17.930 +13:00 [Debug] Start parsing for secret in post body
	2016-01-08 14:46:17.930 +13:00 [Debug] No secret in post body found
	2016-01-08 14:46:17.931 +13:00 [Debug] Start parsing Basic Authentication secret
	2016-01-08 14:46:17.932 +13:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
	iisexpress.exe Information: 0 : 2016-01-08 14:46:17.933 +13:00 [Information] Secret id found: "portal"
	2016-01-08 14:46:17.939 +13:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
	iisexpress.exe Information: 0 : 2016-01-08 14:46:17.940 +13:00 [Information] Client validation success
	iisexpress.exe Information: 0 : 2016-01-08 14:46:17.945 +13:00 [Information] Start token request validation
	iisexpress.exe Information: 0 : 2016-01-08 14:46:17.949 +13:00 [Information] Start password token request validation
	iisexpress.exe Information: 0 : 2016-01-08 14:46:20.296 +13:00 [Information] Password token request validation success.
	iisexpress.exe Information: 0 : 2016-01-08 14:46:20.393 +13:00 [Information] Token request validation success
	 {
	  "ClientId": "portal",
	  "ClientName": "Admin Portal",
	  "GrantType": "password",
	  "Scopes": "api",
	  "UserName": "username",
	  "AuthenticationContextReferenceClasses": [],
	  "Raw": {
		"grant_type": "password",
		"username": "username",
		"password": "******",
		"scope": "api"
	  }
	}
	iisexpress.exe Information: 0 : 2016-01-08 14:46:20.396 +13:00 [Information] Creating token response
	iisexpress.exe Information: 0 : 2016-01-08 14:46:20.397 +13:00 [Information] Processing token request
	2016-01-08 14:46:20.401 +13:00 [Debug] Creating access token
	2016-01-08 14:46:20.407 +13:00 [Debug] Creating reference access token
	iisexpress.exe Information: 0 : 2016-01-08 14:46:20.411 +13:00 [Information] End token request
	iisexpress.exe Information: 0 : 2016-01-08 14:46:20.416 +13:00 [Information] Returning token response.

**Comment by brockallen** [comment]
So no requests to the token validation endpoint. Only thing I can think of is that the SSL connection from the Web API layer is not trusted to IdentityServer. Perhaps a lack of trust configured?

**Comment by aseemflowingly** [comment]
How do I make the MVC application hosting the Identity server to trust the SSL connection from Web API layer?

**Comment by brockallen** [comment]
Do the samples work for you running on those URLs?

Maybe a better approach is to debug the code first if you're not getting any other info from the web api layer.

**Comment by aseemflowingly** [comment]
Yes, the Basic OAuth sample works just fine! I will try to debug the IdentityServer3.AccessTokenValidation code to see if I get anything.

**Comment by aseemflowingly** [comment]
Turns out I needed to refer "Microsoft.Owin.Host.SystemWeb" in my Web API project to get this working.

@brockallen : Thanks for the help!
