### ISSUE TITLE
UseClaimsTransformation and ValidationResultCache

### ISSUE THREAD

**Issue by danielwertheim** [IdentityServer/IdentityServer3.AccessTokenValidation#72]
Enabling using `EnableValidationResultCache = true` and also using `UseClaimsTransformation`, then `UseClaimsTransformation` is called always anyway. And the identity passed into it is not the previously returned identity, so there's no way to exit it. Hence if you lookup `UserInfo` in `UseClaimsTransformation` the identity server will be called... always and you are forced to implement your own caching.

**Comment by brockallen** [comment]
By design it's called on every request. And yes, you might need to implement caching.
