### ISSUE TITLE
Q: WebAPI

### ISSUE THREAD

**Issue by danielwertheim** [IdentityServer/IdentityServer3.AccessTokenValidation#73]
Following your guides on securing an WebAPI using this lib. My questiong is, if the API needs some simple claims like `role`, is there anyway those can be *extracted from the token* so that you don't have to look those claims up using get user info?

**Comment by brockallen** [comment]
You can configure the `Claims` on the `Scope` configuration in IdSvr to include additional claims about the user in the access token.
