### ISSUE TITLE
Does AccessTokenValidation allow for CORS enforcing?

### ISSUE THREAD

**Issue by svrooij** [IdentityServer/IdentityServer3.AccessTokenValidation#83]
Current setup:
- IdentityServer3
- IdentityServer3.Admin
- A lot of Clients defined (including a number of clients developed by thirty party apps)
- One API with AccessTokenValidation

We want to enforce the CORS specified in the IdentityServer on the API, and not just allow every site to use it. Is this possible?

Currently we use [Microsoft.Owin.Cors](https://www.nuget.org/packages/Microsoft.Owin.Cors/)
```csharp
app.UseCors(CorsOptions.AllowAll);
```

**Comment by brockallen** [comment]
We don't so any CORS work in the access token validation MW -- that's up to you.

**Comment by svrooij** [comment]
It would be nice to have an option in the ``app.UseIdentityServerVearerTokenAuthentication(...)`` call to say, ``RegisterIdentityServerCorsPolicy = true``
What would then fetch all registered Cors from IdentityServer and register a CorsPolicy for it, like it does on IdentityServer3 itself.

**Comment by leastprivilege** [comment]
separation of concerns.

That's separate middleware

**Comment by svrooij** [comment]
Do you know if identity server provides something like the .well-known/openid-connect for fetching the Cors?
Willing to create middleware for this purpose.

**Comment by leastprivilege** [comment]
I don't follow.

**Comment by svrooij** [comment]
Can I get a Json file with all the CORS defined in IdentityServer. Or does this need to be build as well.

**Comment by brockallen** [comment]
IdentityServer's allowed CORS origins is for Ajax calls to its endpoints, not your web apis endpoints. If you want your web apis to use the same list, then you'd have to build something to share them.
