### ISSUE TITLE
skipping connection between api and ids in local validation mode

### ISSUE THREAD

**Issue by mbelfer** [IdentityServer/IdentityServer3.AccessTokenValidation#86]
hi,

In a 'Local" validation mode Web Service(API) will connect to Ids server to get public key from Ids server certificate during the startup. Can public key be pre installed so that no connection is done from api to Ids at all in Local mode?

I have a situation where one of my clients wants to host Ids and only wants client devices running locally to connect to it and since api hosted by me outside of there network they do not want me to connect.

thank you
Mark

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
