### ISSUE TITLE
OWIN Implicit flow support

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3.AccessTokenValidation#87]
Is there any package available readily for Implicit or Authorization code flow for MVC applications ? 

Right now I am having to do the following. 

app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = ConfigurationManager.AppSettings["CLIENT_ID"],
                ClientSecret = ConfigurationManager.AppSettings["CLIENT_SECRET"],
                Authority = ConfigurationManager.AppSettings["AUTHORITY"],
                RedirectUri = ConfigurationManager.AppSettings["REDIRECT_URI"],

                // This will give us ID verification as well as Resource verification
                ResponseType = "id_token token",

                // Open ID required for ID verification and default is the application scope.
                Scope = "openid default",

                // The tokens are stored in the cookies within the user session
                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,

                // After logout, identity server will redirect to the application url specified here
                PostLogoutRedirectUri = ConfigurationManager.AppSettings["REDIRECT_URI"],
                Notifications = notifications
            });

**Comment by brockallen** [comment]
> Is there any package available readily for Implicit or Authorization code flow for MVC applications ? 

Yes, the Katana OpenID Connect authentication middleware.

**Comment by aaabdul** [comment]
thanks.
