### ISSUE TITLE
Access to JWT

### ISSUE THREAD

**Issue by neilhosey** [IdentityServer/IdentityServer3.AccessTokenValidation#89]
Hi,

I was wondering is it possible to access the JWT so that we can pass it on further into out API tiers.  

Basically I use reference tokens at the client, and at the API gateway use AccessTokenValidation to retrieve claims and restrict access to the user, which then calls REST services for querying and commands.  But i was wondering if we needed to pass on the token, how would we do this?

Thanks
Neil

**Comment by leastprivilege** [comment]
Sure - RTFM ;)

https://identityserver.github.io/Documentation/docsv2/consuming/options.html
