### ISSUE TITLE
Missing claims in access token

### ISSUE THREAD

**Issue by manjhari** [IdentityServer/IdentityServer3.AccessTokenValidation#91]
Hi,
I have implemented the Resource Owner Flow using a custom local user store implementing IUserService. I also have a custom user AuthenticatedUser() with a List<Claim>. In the AuthenticateLocalAsync method, I retrieve all the users role claims and add to the users claims and return in the AuthenticateResult i.e. 

context.AuthenticateResult = new AuthenticateResult(user.UserID.ToString(), user.DisplayName, user.Claims);

My understanding so far is that these claims should come through in the access token and should be accessible in my API, however they are not coming through. Is there something I am missing?

Thanks

John.

**Comment by brockallen** [comment]
Read the docs, please. That's how how you affect the claims in tokens.
