### ISSUE TITLE
AccessTokenValidation returns "Authorization has been denied for this request" 

### ISSUE THREAD

**Issue by Wesam18** [IdentityServer/IdentityServer3.AccessTokenValidation#99]
I am using AccessTokenValidation version 2.9.1 in a Web API project and it works fine as expected but after a while, days or something, it starts behaving differently and returns "Authorization has been denied for this request"  although I was using a valid token. I checked the Identity server and it didn't receive any validate request from my WebAPI app.

**Comment by leastprivilege** [comment]
You can enable logging to find out more about the real issue. Check the docs.

**Comment by brockallen** [comment]
All set on this issue?
